# -*- coding: utf-8 -*-
"""Activity#2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmvVFTnBun8z3MTl6hdfHEzZHGTgF-D7

#Reading Excel sheet (Seismology.xlsx) from google drive.

#The sheet contains earthquake data in aouth asia from 2015 till 31-01-21
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

"""#Mounting drive and loading excel file

Drop in the excel sheet onto your google drive and read it using pandas
"""

from google.colab import drive
drive.mount('/content/drive')
dataframe = pd.read_excel('/content/drive/MyDrive/Anil Btech - Seismology.xlsx','Sheet1 (2)')
dataframe.head

mag = dataframe['Magnitude.1']
bin_edge=np.arange(1,8.0,0.1)
n, bins, patches = plt.hist(mag, bins =bin_edge,edgecolor="yellow", color="green")

"""Run and see for yourself


---


"""

fx=n/len(mag) #Dividing by total number to get probability from relative frequency
plt.plot(bins[0:len(bins)-1],fx,'r*--')

"""#Task#1:   Compute the expected earthquake magnitude in this time period?


---
#Task#2: What is the probability of earthquake magnitude higher than 5 to occur in the given region?


---



---
"""

#TASK-1
mid_points = (bins[1:] + bins[:-1]) / 2
expected_magnitude = np.sum(mid_points * fx)
print("Expected Magnitude: ", expected_magnitude)

#TASK-2
prob_greater_than_5 = np.sum(fx[mid_points > 5])
print("Probability of earthquake whose Magnitude > 5: ", prob_greater_than_5)

"""#Normal Density:

The excel sheet (*newborn_dummy.xlsx*) contains the birth weight (dummy data) of 5000 newborn babies in a particular hospital. Assuming that the weights are normally distributed

#Task#3: Compute the mean and std. deviation of the distribution. [Hint: Use $\sigma = \sqrt{E(x^2) - E(x)^2}$. Also, in normal distribution function, 68% of the data is inside $1\sigma$.]


#Task#4: Compute the probability  that a baby is no more than 4kg.


---



---
"""

dataframe = pd.read_excel('/content/drive/MyDrive/Anil Btech - newborn_dummy.xlsx')
weights = dataframe['Weight (kg)']
from scipy.stats import norm

# Task-3
mean_weight = np.mean(weights)
variance_weight = np.mean(weights**2) - mean_weight**2
std_dev_weight = np.sqrt(variance_weight)

print("Mean weight: ", mean_weight)
print("Standard deviation: ", std_dev_weight)

#Task - 4
prob_less_than_4kg = norm.cdf(4, loc=mean_weight, scale=std_dev_weight)
print("Probability of weight <= 4kg: ", prob_less_than_4kg)

from google.colab import drive
drive.mount('/content/drive')



"""
#**BONUS (Optional):**
From the excel dataset, extract the earthquakes occurance in India with magnitude above 6.

Compute the average number of events per month.

Plot the histogram of the frequency of months with the number of events.
(Take X as the random variable that gives the number of events/month. Then compute PMF of X.)"""